apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  namespace: news-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding-service
  template:
    metadata:
      labels:
        app: embedding-service
    spec:
      containers:
        - name: embedding-service
          image: newsplatformacr.azurecr.io/embedding-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: news-platform
spec:
  type: ClusterIP
  selector:
    app: embedding-service
  ports:
    - port: 9000
      targetPort: 9000
