apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  namespace: api-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding-service
  template:
    metadata:
      labels:
        app: embedding-service
    spec:
      containers:
        - name: embedding-service
          image: REPLACE_ACR/embedding-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SENTENCE_TRANSFORMER_MODEL
              value: "sentence-transformers/all-MiniLM-L6-v2"
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: api-news
spec:
  selector:
    app: embedding-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
